# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FundooNotes' do
	 use_frameworks!

	pod 'UITextView+Placeholder'
    #pod 'Alamofire', '~> 4.7'
    pod 'MaterialControls', '~> 1.2.2'
    pod 'FBSDKLoginKit'
    

    
end
